import _addSemivoicedMarks from './fn/addSemivoicedMarks';
import _addVoicedMarks from './fn/addVoicedMarks';
import _byteSize from './fn/byteSize';
import _charAt from './fn/charAt';
import _charCodeAt from './fn/charCodeAt';
import _combinateSoundMarks from './fn/combinateSoundMarks';
import _concat from './fn/concat';
import _convertIterationMarks from './fn/convertIterationMarks';
import _convertProlongedSoundMarks from './fn/convertProlongedSoundMarks';
import _endWith from './fn/endWith';
import _has from './fn/has';
import _hasSmallLetter from './fn/hasSmallLetter';
import _hasSurrogatePair from './fn/hasSurrogatePair';
import _hasUnpairedSurrogate from './fn/hasUnpairedSurrogate';
import _includes from './fn/includes';
import _indexOf from './fn/indexOf';
import _is from './fn/is';
import _isEmpty from './fn/isEmpty';
import _isNumeric from './fn/isNumeric';
import _isOnly from './fn/isOnly';
import _isOnlyHiragana from './fn/isOnlyHiragana';
import _isOnlyKatakana from './fn/isOnlyKatakana';
import _lastIndexOf from './fn/lastIndexOf';
import _matches from './fn/matches';
import _naturalKanaOrder from './fn/naturalKanaOrder';
import _naturalKanaSort from './fn/naturalKanaSort';
import _padEnd from './fn/padEnd';
import _padStart from './fn/padStart';
import _remove from './fn/remove';
import _removeUnpairedSurrogate from './fn/removeUnpairedSurrogate';
import _removeVoicedMarks from './fn/removeVoicedMarks';
import _repeat from './fn/repeat';
import _replace from './fn/replace';
import _replaceFromMap from './fn/replaceFromMap';
import _search from './fn/search';
import _slice from './fn/slice';
import _split from './fn/split';
import _startsWith from './fn/startsWith';
import _substr from './fn/substr';
import _substring from './fn/substring';
import _test from './fn/test';
import _toBasicLetter from './fn/toBasicLetter';
import _toHiragana from './fn/toHiragana';
import _toKatakana from './fn/toKatakana';
import _toNarrow from './fn/toNarrow';
import _toNarrowAlphanumeric from './fn/toNarrowAlphanumeric';
import _toNarrowJapanese from './fn/toNarrowJapanese';
import _toNarrowKatakana from './fn/toNarrowKatakana';
import _toNarrowSign from './fn/toNarrowSign';
import _toNarrowSymbolForJapanese from './fn/toNarrowSymbolForJapanese';
import _toNumeric from './fn/toNumeric';
import _toPhoeticKana from './fn/toPhoeticKana';
import _toWide from './fn/toWide';
import _toWideAlphanumeric from './fn/toWideAlphanumeric';
import _toWideJapanese from './fn/toWideJapanese';
import _toWideKatakana from './fn/toWideKatakana';
import _toWideSign from './fn/toWideSign';
import _toWideSymbolForJapanese from './fn/toWideSymbolForJapanese';
import Jaco from './jaco';
// tslint:disable-next-line:no-any
function jaco(str) {
    return new Jaco(str);
}
// tslint:disable:no-namespace no-mergeable-namespace
(function (jaco) {
    'use strict';
    jaco.version = '2.0.0-beta';
    jaco.addSemivoicedMarks = _addSemivoicedMarks;
    jaco.addVoicedMarks = _addVoicedMarks;
    jaco.byteSize = _byteSize;
    jaco.charAt = _charAt;
    jaco.charCodeAt = _charCodeAt;
    jaco.combinateSoundMarks = _combinateSoundMarks;
    jaco.concat = _concat;
    jaco.convertIterationMarks = _convertIterationMarks;
    jaco.convertProlongedSoundMarks = _convertProlongedSoundMarks;
    jaco.endWith = _endWith;
    jaco.has = _has;
    jaco.hasSmallLetter = _hasSmallLetter;
    jaco.hasSurrogatePair = _hasSurrogatePair;
    jaco.hasUnpairedSurrogate = _hasUnpairedSurrogate;
    jaco.includes = _includes;
    jaco.indexOf = _indexOf;
    jaco.is = _is;
    jaco.isEmpty = _isEmpty;
    jaco.isNumeric = _isNumeric;
    jaco.isOnly = _isOnly;
    jaco.isOnlyHiragana = _isOnlyHiragana;
    jaco.isOnlyKatakana = _isOnlyKatakana;
    jaco.lastIndexOf = _lastIndexOf;
    jaco.matches = _matches;
    jaco.naturalKanaOrder = _naturalKanaOrder;
    jaco.naturalKanaSort = _naturalKanaSort;
    jaco.padEnd = _padEnd;
    jaco.padStart = _padStart;
    jaco.remove = _remove;
    jaco.removeUnpairedSurrogate = _removeUnpairedSurrogate;
    jaco.removeVoicedMarks = _removeVoicedMarks;
    jaco.repeat = _repeat;
    jaco.replace = _replace;
    jaco.replaceFromMap = _replaceFromMap;
    jaco.search = _search;
    jaco.slice = _slice;
    jaco.split = _split;
    jaco.startsWith = _startsWith;
    jaco.substr = _substr;
    jaco.substring = _substring;
    jaco.test = _test;
    jaco.toBasicLetter = _toBasicLetter;
    jaco.toHiragana = _toHiragana;
    jaco.toKatakana = _toKatakana;
    jaco.toNarrow = _toNarrow;
    jaco.toNarrowAlphanumeric = _toNarrowAlphanumeric;
    jaco.toNarrowJapanese = _toNarrowJapanese;
    jaco.toNarrowKatakana = _toNarrowKatakana;
    jaco.toNarrowSign = _toNarrowSign;
    jaco.toNarrowSymbolForJapanese = _toNarrowSymbolForJapanese;
    jaco.toNumeric = _toNumeric;
    jaco.toPhoeticKana = _toPhoeticKana;
    jaco.toWide = _toWide;
    jaco.toWideAlphanumeric = _toWideAlphanumeric;
    jaco.toWideJapanese = _toWideJapanese;
    jaco.toWideKatakana = _toWideKatakana;
    jaco.toWideSign = _toWideSign;
    jaco.toWideSymbolForJapanese = _toWideSymbolForJapanese;
})(jaco || (jaco = {}));
// @ts-ignore
window['jaco'] = jaco; // tslint:disable-line:no-string-literal
